#!/bin/bash

latest_tag=$(git describe --tags --abbrev=0)

if ! grep -q -F "## [${latest_tag:1}]" CHANGELOG.md; then
	echo "Error: The latest (## [${latest_tag:1}]) tag was not found in the CHANGELOG.md." 1>&2
	exit 1
fi
