{
 "title": "Sine Wave Example",
 "time": { "from": "1992-12-11T21:00:00.000Z", "to": "1992-12-13T01:00:00.000Z" },
 "templating": {
  "list": [
   { "name": "intervalS", "label": "Aggregation Interval (s)", "query": "400" },
   {
    "name": "cities",
    "label": "Cities",
    "query": "SELECT * FROM (VALUES ('London'), ('New York'), ('Washington'))"
   }
  ]
 },
 "panels": [
  {
   "title": "Time Series With Query Variable",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "queryText": "with data(time, temperature, city) AS (VALUES\n(724125600, 10, 'London'), (724161600, 11, 'London'),\n(724161600, 20, 'New York'), (724197600, 21, 'New York'),\n(724125600, 25, 'Washington'), (724197600, 26, 'Washington')\n) SELECT * from data\nWHERE city in ('London','New York','Washington')\norder by time",
     "rawQueryText": "with data(time, temperature, city) AS (VALUES\n(724125600, 10, 'London'), (724161600, 11, 'London'),\n(724161600, 20, 'New York'), (724197600, 21, 'New York'),\n(724125600, 25, 'Washington'), (724197600, 26, 'Washington')\n) SELECT * from data\nWHERE city in (${cities:singlequote})\norder by time",
     "timeColumns": [ "time" ]
    }
   ]
  },
  {
   "title": "Sine Wave With Variable",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "queryText": "SELECT (time / 500) * 500  as window, avg(value)\nFROM sine_wave\nWHERE time > 724107600000 / 1000 and time <= 724208400000 / 1000\nGROUP BY (time / 500) * 500",
     "rawQueryText": "SELECT $__unixEpochGroupSeconds(time, $intervalS) as window, avg(value)\nFROM sine_wave\nWHERE time > $__from / 1000 and time <= $__to / 1000\nGROUP BY 1\nORDER BY 1 asc",
     "timeColumns": [ "window" ]
    }
   ]
  },
  {
   "title": "Aggregations",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "queryText": "SELECT 1 as time, 4 as value where time >= 1234 and time < 134567",
     "rawQueryText": "SELECT  avg(value), max(value), min(value) from sine_wave where time >= $__from / 1000 and time < $__to / 1000",
     "timeColumns": [ "time" ]
    }
   ]
  },
  {
   "title": "$cities",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 16 },
   "repeat": "cities",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "\n    SELECT CAST(strftime('%s', 'now', '-1 minute') as INTEGER) as time, 4 as value\n    WHERE time >= 1234 and time < 134567\n  ",
     "rawQueryText": "SELECT '$cities' as data "
    }
   ]
  },
  {
   "title": "$cities",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "\n    SELECT CAST(strftime('%s', 'now', '-1 minute') as INTEGER) as time, 4 as value\n    WHERE time >= 1234 and time < 134567\n  ",
     "rawQueryText": "SELECT '$cities' as data "
    }
   ]
  },
  {
   "title": "$cities",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "\n    SELECT CAST(strftime('%s', 'now', '-1 minute') as INTEGER) as time, 4 as value\n    WHERE time >= 1234 and time < 134567\n  ",
     "rawQueryText": "SELECT '$cities' as data "
    }
   ]
  }
 ]
}